CREATE DATABASE :v1;
SET TIME ZONE 'Europe/Belgrade';
\c :v1;
CREATE SCHEMA public;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
\i :v2/db/enums/army-strategy.sql;
\i :v2/db/enums/battle-events.sql;
\i :v2/db/enums/battle-status.sql;
\i :v2/db/functions/timestamp-trigger.sql;
\i :v2/db/tables/battles.sql;
\i :v2/db/tables/armies.sql;
\i :v2/db/tables/battle-logs.sql;
\i :v2/db/functions/set-timestamp-trigger.sql;
